name: Lacak Paket Otomatis

on:
  schedule:
    # Berjalan otomatis setiap 6 menit
    - cron: '0 */6 * * *'
  workflow_dispatch: # Memungkinkan kita tes jalankan manual kapan saja

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Tracker
        env:
          BINDERBYTE_KEY: ${{ secrets.BINDERBYTE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
